config:
  database:
    host: "localhost"
    port: 27017
    user: "root"
    password: "password"

  discord:
    token: "token"
    channel-id: 0

  inventory-sync:
    enable: false
    channel: 0
    old-channel: -1

  enderchest-sync:
    enable: false
    channel: 0
    old-channel: -1